

services:

  app:
    image: golang:1.23
    container_name: go_app
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    command: go run ./cmd/main.go
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cruddatabase
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./init-scripts/initdb.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  dbdata: